fix(core): Missing closing parenthesis
$ rimraf dist && tsc -p ./build/tsconfig.build.json && tsc -p ./build/tsconfig.cli.json && gulp -f ./build/gulpfile.ts build
       src/api/resolvers/admin/promotion.resolver.ts(128,98): error TS1005: ')' expected.
       src/api/resolvers/admin/seller.resolver.ts(67,82): error TS1005: ')' expected.
error Command failed with exit code 2.