chore(core): Revert TypeORM to v0.3.11
v0.3.12 has an issue with migrations not working in Windows. This gets fixed in 0.3.13, but that
version then introduces the problem that custom field eager-loaded relations
fail with

```
TypeORMError: "User__customFields" alias was not found. Maybe you forgot to join it?
```