chore: Update dashboard dependencies & add optionals
Trying to solve failures in Dashboard tests due to
"Error: Cannot find module '../lightningcss.linux-x64-gnu.node'"
Attempting fix based on
https://github.com/parcel-bundler/lightningcss/issues/956#issuecomment-2788862992